// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdQLYyfGnimkoLUAsz5cm6RQwGFG5vVtA',
    appId: '1:905584633551:web:6698e34fdbf62cddf4b9ba',
    messagingSenderId: '905584633551',
    projectId: 'mobileapp-assign',
    authDomain: 'mobileapp-assign.firebaseapp.com',
    storageBucket: 'mobileapp-assign.firebasestorage.app',
    measurementId: 'G-SNVDL2Z40M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe23qTW40Wdx_VPfkGXdwonKDgnfMmOMk',
    appId: '1:905584633551:android:0ac7ec182055ffbff4b9ba',
    messagingSenderId: '905584633551',
    projectId: 'mobileapp-assign',
    storageBucket: 'mobileapp-assign.firebasestorage.app',
  );
}
